[env:esp32cam]
platform = espressif32@5.4.0
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
board_build.partitions = huge_app.csv
board_build.flash_mode = dio
upload_speed = 460800
build_flags =
    -DBOARD_HAS_PSRAM
    -DWIFI_SSID=\"GREEN-BEAN\"
    -DLED_PIN=2
    -DSERIAL_BAUD=115200
    -DWEB_PORT=80
    -DSTREAM_PORT=81
